SELECT jsonb_build_object(
  'authors', (SELECT count(*) FROM authors),
  'works', (SELECT count(*) FROM works),
  'quotes', (SELECT count(*) FROM quotes),
  'quote_originals', (SELECT count(*) FROM quote_originals),
  'sources', (SELECT count(*) FROM sources),
  'editorial_decisions', (SELECT count(*) FROM editorial_decisions),
  'themes', (SELECT count(*) FROM themes),
  'speakers', (SELECT count(*) FROM speakers),
  'voices', (SELECT count(*) FROM voices),
  'quote_audio', (SELECT count(*) FROM quote_audio),
  'publication_runs', (SELECT count(*) FROM publication_runs),
  'work_contributors', (SELECT count(*) FROM work_contributors),
  'author_themes', (SELECT count(*) FROM author_themes),
  'work_themes', (SELECT count(*) FROM work_themes),
  'author_sources', (SELECT count(*) FROM author_sources),
  'work_sources', (SELECT count(*) FROM work_sources),
  'quote_sources', (SELECT count(*) FROM quote_sources),
  'quote_original_sources', (SELECT count(*) FROM quote_original_sources),
  'directus_users', (SELECT count(*) FROM directus_users),
  'directus_roles', (SELECT count(*) FROM directus_roles),
  'directus_policies', (SELECT count(*) FROM directus_policies),
  'directus_permissions', (SELECT count(*) FROM directus_permissions),
  'directus_presets', (SELECT count(*) FROM directus_presets)
);
